--------------------------------------------------------
--  File created - Tuesday-April-12-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ENTERTAINER_ENTERTAINER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER_ENTERTAINER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence FLOURIST_FLOURIST_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST_FLOURIST_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence MUSICIAN_MUSICIAN_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN_MUSICIAN_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence PHOTOGRAPHER_PHOTO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER_PHOTO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CITY" 
   (	"C_CITY" VARCHAR2(50 CHAR), 
	"C_STATE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITY_LOG
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CITY_LOG" 
   (	"TYPEOF" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EXACTTIME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" 
   (	"C_LASTNAME" VARCHAR2(50 CHAR), 
	"C_FIRSTNAME" VARCHAR2(50 CHAR), 
	"C_PHONE" VARCHAR2(50 CHAR), 
	"C_TYPE" VARCHAR2(50 CHAR), 
	"ZIP_ZIP" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COST
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" 
   (	"COST" VARCHAR2(50 CHAR), 
	"PRICE" VARCHAR2(50 CHAR), 
	"MUSICIAN_MUS_CONTACT" VARCHAR2(50 CHAR), 
	"FLOURIST_F_CONTACT" VARCHAR2(50 CHAR), 
	"PHOTOGRAPHER_P_CONTACT" VARCHAR2(50 CHAR), 
	"ENTERTAINER_ENTERTAINER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTERTAINER
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" 
   (	"ENT_NAME" VARCHAR2(50 CHAR), 
	"ENT_CONTACT" VARCHAR2(50 CHAR), 
	"ENTERTAINER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" 
   (	"E_DATE" VARCHAR2(50 CHAR), 
	"E_TYPE" VARCHAR2(50 CHAR), 
	"E_STARTTIME" VARCHAR2(50 CHAR), 
	"E_DURATION" VARCHAR2(50 CHAR), 
	"CLIENT_C_LASTNAME" VARCHAR2(50 CHAR), 
	"CLIENT_C_FIRSTNAME" VARCHAR2(50 CHAR), 
	"LOCATION_L_TYPE" VARCHAR2(50 CHAR), 
	"MUSICIAN_MUS_CONTACT" VARCHAR2(50 CHAR), 
	"FLOURIST_F_CONTACT" VARCHAR2(50 CHAR), 
	"PHOTOGRAPHER_P_CONTACT" VARCHAR2(50 CHAR), 
	"LOCATION_L_NAME" VARCHAR2(50 CHAR), 
	"ENTERTAINER_ENT_CONTACT" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLOURIST
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" 
   (	"F_NAME" VARCHAR2(50 CHAR), 
	"F_CONTACT" VARCHAR2(50 CHAR), 
	"FLOURIST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" 
   (	"L_NAME" VARCHAR2(50 CHAR), 
	"L_TYPE" VARCHAR2(50 CHAR), 
	"L_NOOFGUESTS" VARCHAR2(50 CHAR), 
	"ADDRESS" VARCHAR2(50 CHAR), 
	"EVENT_E_DATE" VARCHAR2(50 CHAR), 
	"EVENT_E_TYPE" VARCHAR2(50 CHAR), 
	"EVENT_E_STARTTIME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" 
   (	"M_MenuNo." VARCHAR2(50 CHAR), 
	"M_APPETIZER" VARCHAR2(50 CHAR), 
	"M_SALADS" VARCHAR2(50 CHAR), 
	"M_MAIN" VARCHAR2(50 CHAR), 
	"M_DESSERT" VARCHAR2(50 CHAR), 
	"EVENT_E_DATE" VARCHAR2(50 CHAR), 
	"EVENT_E_TYPE" VARCHAR2(50 CHAR), 
	"EVENT_E_STARTTIME" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUSICIAN
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" 
   (	"MUS_NAME" VARCHAR2(50 CHAR), 
	"MUS_TYPE" VARCHAR2(50 CHAR), 
	"MUS_CONTACT" VARCHAR2(50 CHAR), 
	"MUSICIAN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHOTOGRAPHER
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" 
   (	"P_NAME" VARCHAR2(50 CHAR), 
	"P_CONTACT" VARCHAR2(50 CHAR), 
	"PHOTO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZIP
--------------------------------------------------------

  CREATE TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" 
   (	"ZIP" VARCHAR2(50 CHAR), 
	"C_CITY" VARCHAR2(50 CHAR), 
	"C_STATE" VARCHAR2(50 CHAR), 
	"CITY_C_CITY" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.CITY
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.CITY (C_CITY,C_STATE) values ('Silver Spring','MD');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CITY (C_CITY,C_STATE) values ('Washington','DC');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CITY (C_CITY,C_STATE) values ('Lorton','VA');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CITY (C_CITY,C_STATE) values ('Fairfac','VA');
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.CITY_LOG
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.CITY_LOG (TYPEOF,USERNAME,EXACTTIME) values ('Insert','GRP4_DEVANSHU_M_IND_PROJ','12-APR-16');
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.CLIENT
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.CLIENT (C_LASTNAME,C_FIRSTNAME,C_PHONE,C_TYPE,ZIP_ZIP) values ('Matlawala','Devanshu','123','Business','20910');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CLIENT (C_LASTNAME,C_FIRSTNAME,C_PHONE,C_TYPE,ZIP_ZIP) values ('Patel','Akash','123','Business','20910');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CLIENT (C_LASTNAME,C_FIRSTNAME,C_PHONE,C_TYPE,ZIP_ZIP) values ('Patel','Maulik','123','Business','20911');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CLIENT (C_LASTNAME,C_FIRSTNAME,C_PHONE,C_TYPE,ZIP_ZIP) values ('Patel','Aman','123','Business','20910');
Insert into GRP4_DEVANSHU_M_IND_PROJ.CLIENT (C_LASTNAME,C_FIRSTNAME,C_PHONE,C_TYPE,ZIP_ZIP) values ('Mehta','Akash','123','Individual','20037');
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.COST
SET DEFINE OFF;
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.ENTERTAINER
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.ENTERTAINER (ENT_NAME,ENT_CONTACT,ENTERTAINER_ID) values ('Anil','193',1);
Insert into GRP4_DEVANSHU_M_IND_PROJ.ENTERTAINER (ENT_NAME,ENT_CONTACT,ENTERTAINER_ID) values ('Mukesh','347',2);
Insert into GRP4_DEVANSHU_M_IND_PROJ.ENTERTAINER (ENT_NAME,ENT_CONTACT,ENTERTAINER_ID) values ('Dhirubhai','764',3);
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.EVENT
SET DEFINE OFF;
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.FLOURIST
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.FLOURIST (F_NAME,F_CONTACT,FLOURIST_ID) values ('Yoshita','789',1);
Insert into GRP4_DEVANSHU_M_IND_PROJ.FLOURIST (F_NAME,F_CONTACT,FLOURIST_ID) values ('Manoj','576',2);
Insert into GRP4_DEVANSHU_M_IND_PROJ.FLOURIST (F_NAME,F_CONTACT,FLOURIST_ID) values ('Yash','345',3);
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.LOCATION
SET DEFINE OFF;
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.MENU
SET DEFINE OFF;
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.MUSICIAN
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.MUSICIAN (MUS_NAME,MUS_TYPE,MUS_CONTACT,MUSICIAN_ID) values ('Deadmau5','EDM','123',1);
Insert into GRP4_DEVANSHU_M_IND_PROJ.MUSICIAN (MUS_NAME,MUS_TYPE,MUS_CONTACT,MUSICIAN_ID) values ('Deadmau4','EDM','456',2);
Insert into GRP4_DEVANSHU_M_IND_PROJ.MUSICIAN (MUS_NAME,MUS_TYPE,MUS_CONTACT,MUSICIAN_ID) values ('Deadmau2','EDM','789',3);
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.PHOTOGRAPHER
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.PHOTOGRAPHER (P_NAME,P_CONTACT,PHOTO_ID) values ('Doremon','123',4);
Insert into GRP4_DEVANSHU_M_IND_PROJ.PHOTOGRAPHER (P_NAME,P_CONTACT,PHOTO_ID) values ('Pichaku','456',5);
Insert into GRP4_DEVANSHU_M_IND_PROJ.PHOTOGRAPHER (P_NAME,P_CONTACT,PHOTO_ID) values ('Chota Bheem','789',6);
REM INSERTING into GRP4_DEVANSHU_M_IND_PROJ.ZIP
SET DEFINE OFF;
Insert into GRP4_DEVANSHU_M_IND_PROJ.ZIP (ZIP,C_CITY,C_STATE,CITY_C_CITY) values ('20910','Silver Spring','MD','Silver Spring');
Insert into GRP4_DEVANSHU_M_IND_PROJ.ZIP (ZIP,C_CITY,C_STATE,CITY_C_CITY) values ('20911','Silver Spring','MD','Silver Spring');
Insert into GRP4_DEVANSHU_M_IND_PROJ.ZIP (ZIP,C_CITY,C_STATE,CITY_C_CITY) values ('20037','Washington','DC','Washington');
Insert into GRP4_DEVANSHU_M_IND_PROJ.ZIP (ZIP,C_CITY,C_STATE,CITY_C_CITY) values ('20938','Washington','DC','Washington');
Insert into GRP4_DEVANSHU_M_IND_PROJ.ZIP (ZIP,C_CITY,C_STATE,CITY_C_CITY) values ('20079','Lorton','VA','Lorton');
--------------------------------------------------------
--  DDL for Index CLIENT_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT_UNIQUE" ON "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" ("C_LASTNAME", "C_FIRSTNAME", "C_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLOURIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" ("F_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTERTAINER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" ("ENTERTAINER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."COST_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."COST" ("COST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."EVENT_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("E_DATE", "E_TYPE", "E_STARTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT__IDXV2
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."EVENT__IDXV2" ON "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("FLOURIST_F_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT__IDXV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."EVENT__IDXV1" ON "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("MUSICIAN_MUS_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."EVENT__IDX" ON "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("LOCATION_L_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."MENU_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."MENU" ("M_MenuNo.") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" ("L_TYPE", "L_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUSICIAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" ("MUS_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."CITY_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."CITY" ("C_CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATION__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION__IDX" ON "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" ("EVENT_E_DATE", "EVENT_E_TYPE", "EVENT_E_STARTTIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT__IDXV3
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."EVENT__IDXV3" ON "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("PHOTOGRAPHER_P_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZIP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."ZIP_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" ("ZIP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHOTOGRAPHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" ("P_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT_PK" ON "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" ("C_LASTNAME", "C_FIRSTNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT__IDXV4
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."EVENT__IDXV4" ON "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("ENTERTAINER_ENT_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTERTAINER_PKV1
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER_PKV1" ON "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" ("ENT_CONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("E_DATE", "E_TYPE", "E_STARTTIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("ENTERTAINER_ENT_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("LOCATION_L_NAME" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("PHOTOGRAPHER_P_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("FLOURIST_F_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("MUSICIAN_MUS_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("LOCATION_L_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("E_DURATION" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("E_STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("E_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" MODIFY ("E_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CITY" ADD CONSTRAINT "CITY_PK" PRIMARY KEY ("C_CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CITY" MODIFY ("C_CITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHOTOGRAPHER
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" ADD CONSTRAINT "PHOTOGRAPHER_PK" PRIMARY KEY ("P_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" MODIFY ("P_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" MODIFY ("P_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("C_LASTNAME", "C_FIRSTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" MODIFY ("ZIP_ZIP" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" MODIFY ("C_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" MODIFY ("C_FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" MODIFY ("C_LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_UNIQUE" UNIQUE ("C_LASTNAME", "C_FIRSTNAME", "C_PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("L_TYPE", "L_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("EVENT_E_STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("EVENT_E_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("EVENT_E_DATE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("L_NOOFGUESTS" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("L_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" MODIFY ("L_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("M_MenuNo.")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("EVENT_E_STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("EVENT_E_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("EVENT_E_DATE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("M_DESSERT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("M_MAIN" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("M_SALADS" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("M_APPETIZER" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" MODIFY ("M_MenuNo." NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COST
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" ADD CONSTRAINT "COST_PK" PRIMARY KEY ("COST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" MODIFY ("ENTERTAINER_ENTERTAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" MODIFY ("PHOTOGRAPHER_P_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" MODIFY ("FLOURIST_F_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" MODIFY ("MUSICIAN_MUS_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" MODIFY ("COST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTERTAINER
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" ADD CONSTRAINT "ENTERTAINER_PK" UNIQUE ("ENTERTAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" ADD CONSTRAINT "ENTERTAINER_PKV1" PRIMARY KEY ("ENT_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" MODIFY ("ENTERTAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" MODIFY ("ENT_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" MODIFY ("ENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZIP
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" ADD CONSTRAINT "ZIP_PK" PRIMARY KEY ("ZIP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" MODIFY ("CITY_C_CITY" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" MODIFY ("C_STATE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" MODIFY ("C_CITY" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" MODIFY ("ZIP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FLOURIST
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" ADD CONSTRAINT "FLOURIST_PK" PRIMARY KEY ("F_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" MODIFY ("F_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" MODIFY ("F_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUSICIAN
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" ADD CONSTRAINT "MUSICIAN_PK" PRIMARY KEY ("MUS_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" MODIFY ("MUS_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" MODIFY ("MUS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" MODIFY ("MUS_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_ZIP_FK" FOREIGN KEY ("ZIP_ZIP")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" ("ZIP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COST
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" ADD CONSTRAINT "COST_FLOURIST_FK" FOREIGN KEY ("FLOURIST_F_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" ("F_CONTACT") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" ADD CONSTRAINT "COST_MUSICIAN_FK" FOREIGN KEY ("MUSICIAN_MUS_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" ("MUS_CONTACT") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."COST" ADD CONSTRAINT "COST_PHOTOGRAPHER_FK" FOREIGN KEY ("PHOTOGRAPHER_P_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" ("P_CONTACT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_CLIENT_FK" FOREIGN KEY ("CLIENT_C_LASTNAME", "CLIENT_C_FIRSTNAME")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."CLIENT" ("C_LASTNAME", "C_FIRSTNAME") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_ENTERTAINER_FK" FOREIGN KEY ("ENTERTAINER_ENT_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER" ("ENT_CONTACT") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FLOURIST_FK" FOREIGN KEY ("FLOURIST_F_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST" ("F_CONTACT") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_LOCATION_FK" FOREIGN KEY ("LOCATION_L_TYPE", "LOCATION_L_NAME")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" ("L_TYPE", "L_NAME") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_MUSICIAN_FK" FOREIGN KEY ("MUSICIAN_MUS_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN" ("MUS_CONTACT") ENABLE;
  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_PHOTOGRAPHER_FK" FOREIGN KEY ("PHOTOGRAPHER_P_CONTACT")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER" ("P_CONTACT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."LOCATION" ADD CONSTRAINT "LOCATION_EVENT_FK" FOREIGN KEY ("EVENT_E_DATE", "EVENT_E_TYPE", "EVENT_E_STARTTIME")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("E_DATE", "E_TYPE", "E_STARTTIME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."MENU" ADD CONSTRAINT "MENU_EVENT_FK" FOREIGN KEY ("EVENT_E_DATE", "EVENT_E_TYPE", "EVENT_E_STARTTIME")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."EVENT" ("E_DATE", "E_TYPE", "E_STARTTIME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZIP
--------------------------------------------------------

  ALTER TABLE "GRP4_DEVANSHU_M_IND_PROJ"."ZIP" ADD CONSTRAINT "ZIP_CITY_FK" FOREIGN KEY ("CITY_C_CITY")
	  REFERENCES "GRP4_DEVANSHU_M_IND_PROJ"."CITY" ("C_CITY") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CITY_AUDIT_TRIG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."CITY_AUDIT_TRIG" 
  BEFORE INSERT OR UPDATE ON CITY
  FOR EACH ROW
BEGIN
	If INSERTING then
    insert into city_log values('Insert',user,sysdate);
	end if;
	
	if UPDATING then
    insert into city_log values('Update',user,sysdate);
	end if;
END;


insert into city values('Fairfac', 'VA');

select*from city;

select*from city_log;
/
ALTER TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."CITY_AUDIT_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ENTERTAINER_ENTERTAINER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER_ENTERTAINER_ID_TRG" BEFORE
  INSERT ON Entertainer FOR EACH ROW  WHEN (NEW.Entertainer_ID IS NULL) BEGIN :NEW.Entertainer_ID := Entertainer_Entertainer_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."ENTERTAINER_ENTERTAINER_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FLOURIST_FLOURIST_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST_FLOURIST_ID_TRG" BEFORE
  INSERT ON Flourist FOR EACH ROW  WHEN (NEW.Flourist_ID IS NULL) BEGIN :NEW.Flourist_ID := Flourist_Flourist_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."FLOURIST_FLOURIST_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MUSICIAN_MUSICIAN_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN_MUSICIAN_ID_TRG" BEFORE
  INSERT ON Musician FOR EACH ROW  WHEN (NEW.Musician_ID IS NULL) BEGIN :NEW.Musician_ID := Musician_Musician_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."MUSICIAN_MUSICIAN_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PHOTOGRAPHER_PHOTO_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER_PHOTO_ID_TRG" BEFORE
  INSERT ON Photographer FOR EACH ROW  WHEN (NEW.Photo_ID IS NULL) BEGIN :NEW.Photo_ID := Photographer_Photo_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "GRP4_DEVANSHU_M_IND_PROJ"."PHOTOGRAPHER_PHOTO_ID_TRG" ENABLE;
